name: Run Application

on:
  workflow_dispatch:
    inputs:
      environment:
        description: '실행할 환경 선택'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - prod

jobs:
  run-frontend:
    name: Run Frontend
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'dev'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Dependencies
      run: |
        cd my-app
        npm install
        
    - name: Start Frontend
      run: |
        cd my-app
        npm start

  run-backend:
    name: Run Backend
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'dev'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Grant execute permission for mvnw
      run: |
        cd Backend/Backend
        chmod +x mvnw
        
    - name: Run Spring Boot
      run: |
        cd Backend/Backend
        ./mvnw spring-boot:run -Dserver.port=9999 